name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'

jobs:
  build_and_test:
    name: Build and Run Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0
      
    - name: Use Node.js 22
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Abstract Factory Test
      run: npm run start01
      
    - name: Run Builder Test
      run: npm run start02